# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Clusters_2026',
                'doc_host': 'https://msalazarcgeo.github.io',
                'git_url': 'https://github.com/msalazarcgeo/Clusters_2026',
                'lib_path': 'Clusters_2026'},
  'syms': {'Clusters_2026.core': {'Clusters_2026.core.foo': ('core.html#foo', 'Clusters_2026/core.py')}}}
